# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile.rb, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{beefdump}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Thorben Schr\303\266der"]
  s.date = %q{2010-07-07}
  s.description = %q{A testbed for non-player character AI in role-playing games.}
  s.email = %q{stillepost@gmail.com}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "lib/beefdump.rb",
     "lib/beefdump/boot.rb",
     "lib/beefdump/client/base.rb",
     "lib/beefdump/client/graphical/client.rb",
     "lib/beefdump/client/graphical/window.rb",
     "lib/beefdump/config/base.rb",
     "lib/beefdump/config/blueprint.rb",
     "lib/beefdump/game/base.rb",
     "lib/beefdump/game/player.rb",
     "lib/beefdump/game/state.rb",
     "lib/beefdump/logger.rb",
     "lib/beefdump/map/layer.rb",
     "lib/beefdump/map/map.rb",
     "lib/beefdump/map/object.rb",
     "lib/beefdump/map/tileset.rb",
     "lib/beefdump/monkey_patches/open_struct.rb",
     "lib/beefdump/monkey_patches/string.rb",
     "lib/beefdump/utils/image_util.rb",
     "lib/beefdump/world/entity.rb",
     "lib/beefdump/world/object.rb",
     "lib/beefdump/world/object_property.rb",
     "lib/beefdump/world/player.rb",
     "lib/beefdump/world/world.rb"
  ]
  s.homepage = %q{http://github.com/walski/beefdump}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A testbed for non-player character AI in role-playing games.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<xml-simple>, [">= 0"])
    else
      s.add_dependency(%q<xml-simple>, [">= 0"])
    end
  else
    s.add_dependency(%q<xml-simple>, [">= 0"])
  end
end

